#!/usr/bin/env python3
"""Generate sitemap.md: every page as a live github.io link, plus a local
broken-link check.

Walks the repo for HTML pages, turns each into its production URL
(https://pitrified.github.io/...), and writes a single browsable markdown
page. Then it parses every internal link/asset reference (``href`` / ``src`` /
``data`` starting with ``/``) and flags any that don't resolve to a file on
disk - a fast, offline way to catch broken links before pushing.

Usage:
    python3 tools/gen_sitemap.py            # writes sitemap.md
    python3 tools/gen_sitemap.py --check    # only check links, exit 1 if broken
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

BASE_URL = "https://pitrified.github.io"
ROOT = Path(__file__).resolve().parent.parent

# Preferred ordering for the sitemap; pages not listed are appended, sorted.
PAGE_ORDER = [
    "",
    "simulation",
    "recipes",
    "language-learning",
    "travel",
    "xr",
    "misc",
    "libraries",
    "infra",
    "about",
    "all",
]

_TITLE_RE = re.compile(r"<title>(.*?)</title>", re.IGNORECASE | re.DOTALL)
_REF_RE = re.compile(r"""(?:href|src|data)\s*=\s*["']([^"']+)["']""", re.IGNORECASE)


def find_pages() -> list[Path]:
    """All .html files in the repo (skipping dot-dirs)."""
    return sorted(
        p
        for p in ROOT.rglob("*.html")
        if not any(part.startswith(".") for part in p.relative_to(ROOT).parts)
    )


def url_path(page: Path) -> str:
    """Map an .html file to its clean URL path ('' is the site root)."""
    rel = page.relative_to(ROOT)
    if rel.name == "index.html":
        parent = rel.parent
        return "" if parent == Path(".") else f"{parent.as_posix()}/"
    return rel.as_posix()


def page_title(page: Path) -> str:
    m = _TITLE_RE.search(page.read_text(encoding="utf-8"))
    return re.sub(r"\s+", " ", m.group(1)).strip() if m else page.stem


def resolve_internal(ref: str) -> Path | None:
    """Resolve a root-absolute reference to the file it should serve, or None
    if it isn't a local internal link (external URL, data:, #anchor, mailto)."""
    ref = ref.split("#", 1)[0].split("?", 1)[0]
    if not ref.startswith("/"):
        return None  # external, relative, data:, mailto:, etc.
    rel = ref.lstrip("/")
    target = ROOT / rel
    if ref.endswith("/") or target.is_dir():
        target = target / "index.html"
    return target


def check_links(pages: list[Path]) -> list[tuple[str, str]]:
    """Return (source_page_url, broken_ref) for each unresolved internal link."""
    broken: list[tuple[str, str]] = []
    for page in pages:
        src_url = "/" + url_path(page)
        for ref in _REF_RE.findall(page.read_text(encoding="utf-8")):
            target = resolve_internal(ref)
            if target is not None and not target.exists():
                broken.append((src_url, ref))
    return broken


def build_sitemap(pages: list[Path], broken: list[tuple[str, str]]) -> str:
    order = {name: i for i, name in enumerate(PAGE_ORDER)}

    def sort_key(page: Path) -> tuple[int, str]:
        path = url_path(page).rstrip("/")
        return (order.get(path, len(order)), path)

    lines = [
        "# Sitemap",
        "",
        "_Auto-generated by `make sitemap` - do not edit by hand._",
        "",
        f"All pages of [{BASE_URL}]({BASE_URL}/), as live links.",
        "",
    ]
    for page in sorted(pages, key=sort_key):
        path = url_path(page)
        url = f"{BASE_URL}/{path}"
        label = "/" if path == "" else f"/{path}"
        lines.append(f"- [{label}]({url}) - {page_title(page)}")

    lines.append("")
    if broken:
        lines.append("## ⚠ Broken internal links")
        lines.append("")
        for src_url, ref in broken:
            lines.append(f"- `{ref}` referenced from `{src_url}` - target missing")
        lines.append("")
    else:
        lines.append("_No broken internal links._")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="only run the broken-link check; exit 1 if any are found",
    )
    args = parser.parse_args()

    pages = find_pages()
    broken = check_links(pages)

    if args.check:
        if broken:
            for src_url, ref in broken:
                print(f"BROKEN: {ref} (from {src_url})", file=sys.stderr)
            sys.exit(1)
        print(f"ok - {len(pages)} pages, no broken internal links")
        return

    out = ROOT / "sitemap.md"
    out.write_text(build_sitemap(pages, broken) + "\n", encoding="utf-8")
    status = f"{len(broken)} broken" if broken else "no broken links"
    print(f"wrote {out.relative_to(ROOT)} - {len(pages)} pages, {status}")
    if broken:
        sys.exit(1)


if __name__ == "__main__":
    main()
